name: Commit
description: Commits the build
inputs:
  project:
    required: true
    description: The output of the check action

# TODO: make this a post action of restore
runs:
  using: composite
  steps:
    # Using a different version of tar from windows causes a cache miss with linux
    # https://github.com/actions/cache/issues/576#issuecomment-830796954
    - name: "Use GNU tar instead BSD tar"
      shell: cmd
      run: |
        echo C:\Program Files\Git\usr\bin>>"%GITHUB_PATH%"
        where zstd
      if: runner.os == 'Windows'

    - name: Save cache
      uses: martijnhols/actions-cache/save@204c5fc6f17f75fc56021276acb5aa4b6a051d8e
      with:
        path: ${{fromJson(inputs.project).path}}
        key: ${{fromJson(inputs.project).key}}
