name: Commit
description: Commits the build
inputs:
  key:
    description: The key that was produced by set-up
    required: true
  path:
    description: The path to be committed, must match output-path of set-up
    required: false
    default: __dummy_value__
# TODO: make this a post step of set-up

runs:
  using: composite
  steps:
    - run: touch __dummy_value__
      shell: bash
      if: inputs.path == '__dummy_value__'

    - name: Save cache
      uses: martijnhols/actions-cache/save@204c5fc6f17f75fc56021276acb5aa4b6a051d8e
      with:
        path: ${{inputs.path}}
        key: ${{inputs.key}}
